version: '3.8'

services:
  redis:
    image: redis:7.2-alpine
    container_name: parser-redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build: .
    container_name: parser
    ports:
      - 8000:8000
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SELENIUM_REMOTE_URL=http://chrome:4444/wd/hub
    depends_on:
      chrome:
        condition: service_healthy
      redis:
        condition: service_healthy
      
  chrome:
    image: selenium/standalone-chrome:latest
    container_name: parser-chrome
    ports:
      - "4444:4444"
    shm_size: 2gb
    restart: unless-stopped

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/status"]
      interval: 10s
      timeout: 10s
      retries: 3
volumes:
  redis-data:
